{
  "name": "ClientBox Docs",
  "logo": {
    "light": "/logo/light.svg",
    "dark": "/logo/dark.svg"
  },
  "favicon": "/favicon.png",
  "colors": {
    "primary": "#0D99FF",
    "light": "#FFFFFF",
    "dark": "#000000"
  },
  "navigation": [
    {
      "group": "API Reference",
      "pages": [
        "openapi"
      ]
    }
  ],
  "openapi": "openapi.yaml"
}
